{{- with .Values.imageProcessingService }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .label }}
  namespace: {{ $.Values.global.namespace }}
spec:
  replicas: {{ .replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .rollingUpdate.maxSurge }}
      maxUnavailable: {{ .rollingUpdate.maxUnavailable }}
  selector:
    matchLabels:
      app: {{ .label }}
  template:
    metadata:
      labels:
        app: {{ .label }}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: {{ .label }}
                topologyKey: kubernetes.io/hostname
      imagePullSecrets:
        - name: {{ $.Values.secrets.imagePullSecret }}
      containers:
        - name: {{ .label }}
          image: "{{ $.Values.global.harborRegistry }}/{{ .image }}:{{ $.Values.global.imageTag }}"
          env:
            - name: RABBITMQ_HEALTH_FILE
              value: "/tmp/healthy"
            - name: OBJECT_STORAGE_ACCOUNT_ID
              value: "{{ .accountId }}"
          envFrom:
            - configMapRef:
                name: {{ $.Values.configMap.name }}
            - secretRef:
                name: {{ $.Values.secrets.credentials.db }}
            - secretRef:
                name: {{ $.Values.secrets.credentials.objectStorage }}
            - secretRef:
                name: {{ $.Values.secrets.credentials.rabbitMQ }}
          resources:
            requests:
              cpu: {{ .resources.requests.cpu }}
              memory: {{ .resources.requests.memory }}
            limits:
              cpu: {{ .resources.limits.cpu }}
              memory: {{ .resources.limits.memory }}
          livenessProbe:
            exec:
              command: ["sh", "-c", "find /tmp/healthy -mmin -2 | grep -q ."]
            initialDelaySeconds: 15
            periodSeconds: 30
{{- end }}
